using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using HotelModel.DB_Conn_DSL;
using System.Data.SqlClient;
using System.Data;
using System.Windows.Forms;

namespace HotelModel.Home
{
    public static class CountryModel
    {

        /* Defining sql accessors: Snippet Autogenerated */
        private static DataSet _country;
        private static SqlDataAdapter _country_adapter;
        public static SqlDataAdapter country_adapter { get { if ((country == null) || true); return _country_adapter; } }
        public static DataSet country{
            get
            {
                if (_country == null)
                {
                    _country_adapter = (SqlDataAdapter) new SqlQuery("SELECT country FROM BOBBY_TABLES.COUNTRIES;").AsDataAdapter().Execute()["ReturnedValues"];
                    _country = new DataSet();
                    _country_adapter.Fill(_country);
                } 
                return _country;
            }
        }

        public static void BindTo(ComboBox ctrl)
        {
            ctrl.DataSource = country.Tables[0];
            ctrl.ValueMember = "country";
            ctrl.DisplayMember = "country";
        }
        
    }
}
